### PR TITLE
Release/v2.0.0

### PR DESCRIPTION
**Pull request by michaloo**
* **BREAKING** HullClient is a set of ES6 classes now, not a Function anymore - this means you cannot do `const hullClient = HullClient()` anymore, you always need `new` keyword
* **BREAKING** `as` method is not available anymore, use `asUser`
* **BREAKING** `utils.groupTraits` method is not available anymore, use `utils.traits.group`
* **BREAKING** `traits` method second parameter accepting `source` and `sync` option is not available anymore. Sync calls are not available at all, and if you need to apply `source` to your traits you need to do it before passing payload to `traits` method
* **BREAKING** `hullClient.api.get` methods are not available anymore, use `hullClient.get` or `hullClient.api(path, "get")`, the same applies for all HTTP verbs
* the client now comes with full set of Flow types in src/types.js file
  ```js
  import type { HullUserClaims } from "hull-client";

  const userClaims: HullUserClaims = {
    wrong_claim: "bar"
  };
  // this will throw flow check error since `wrong_claim` is not correct
  ```
* underlying HTTP library restler was replaced with superagent

### CODE REVIEW

**Comment by michaloo** [comment]
@sbellity I wanted to confirm one thing with you.
The `alias` method takes user claims as a payload?
https://github.com/hull/hull-client-node/blob/develop/src/client.js#L338
so we could type the method argument with following type?
https://github.com/hull/hull-client-node/blob/develop/src/types.js#L95

**Comment by unity** [comment]
What is the motivation for removing the “source” option from “track”? I think deprecating it is creating some consistency issues with the “track” calls that also have a source field, and removes the possibility to restrict some namespaces in the future, or change the key format.

**Comment by unity** [comment]
Sorry. “Remove from “traits””

**Comment by michaloo** [comment]
I've put the reasoning here: https://github.com/hull/infra/pull/13#issuecomment-389174225

> I'm also thinking about removing `source` option from traits since it's very rarely used in connectors since most of them also try to setIfNull top level traits and in my opinion this last-time transformation may be confusing. Without `source` the behavior is "what you send is what you get", but when passing `source` developer cannot see what was the actual payload. We can provide some utility to support current usage if this is done somewhere.

I see the inconsistency between `track` and `traits`, but still `source` on `traits` was doing something else, manipulating and mutating the payload in a nontransparent way. From the connector perspective this feature should be responsibility of a mapping utility which builds the payload.
If we think about the longterm "raw input" idea we could get the consistency with `track` again, so to send the raw payload and add some additional header or claim marking what is the source.

**Comment by michaloo** [comment]
Hm, actually probably there is one current usage of this option - processor codes.

**Comment by sbellity** [comment]
@michaloo actually no, the alias traits take a string to alias the user to. I believe it's currently used like this : 

```javascript
hull.asUser({ email: 'michal@hull.io' }).alias({ anonymous_id: 'michaloo' })
```

but could be simplified as : 

```javascript
hull.asUser({ email: 'michal@hull.io' }).alias('michaloo')
```

**Comment by michaloo** [comment]
@SMK1085 as you can see in this PR I proposed removing `source: string` option from `traits` method, since from connectors perspective is not a good practise. But I see that it may be a crucial feature for some processor codes.
Do you know it's the case that customers are using this option to prepend the traits names? Do you think we could introduce utility function to do it before calling traits? I know it may introduce more complexity to the scripts so I'm thinking how to make the whole thing smooth for us and for customers.

**Pull request merged**
